### ISSUE TITLE
 java.io.IOException: read failed, socket might closed or timeout, read ret: -1

### ISSUE THREAD

**Issue by pranaypatel512** [massimoca/OBDReader#1]
Thanks for nice OBD example.
While clicking on Bluetooth device to connect I am getting following error log.
`04-05 16:31:37.138 10951-10951/com.massimoc.obdreader W/BluetoothAdapter: getBluetoothService() called with no BluetoothManagerCallback
04-05 16:31:37.247 10951-10951/com.massimoc.obdreader W/System.err: java.io.IOException: read failed, socket might closed or timeout, read ret: -1
04-05 16:31:37.264 10951-10951/com.massimoc.obdreader W/System.err:     at android.bluetooth.BluetoothSocket.readAll(BluetoothSocket.java:517)
04-05 16:31:37.264 10951-10951/com.massimoc.obdreader W/System.err:     at android.bluetooth.BluetoothSocket.waitSocketSignal(BluetoothSocket.java:494)
04-05 16:31:37.264 10951-10951/com.massimoc.obdreader W/System.err:     at android.bluetooth.BluetoothSocket.connect(BluetoothSocket.java:324)
04-05 16:31:37.264 10951-10951/com.massimoc.obdreader W/System.err:     at com.massimoc.obdreader.ConnectThread.executeConnection(ConnectThread.java:76)
04-05 16:31:37.264 10951-10951/com.massimoc.obdreader W/System.err:     at com.massimoc.obdreader.BluetoothActivity$2.onItemClick(BluetoothActivity.java:131)
04-05 16:31:37.264 10951-10951/com.massimoc.obdreader W/System.err:     at android.widget.AdapterView.performItemClick(AdapterView.java:300)
04-05 16:31:37.264 10951-10951/com.massimoc.obdreader W/System.err:     at android.widget.AbsListView.performItemClick(AbsListView.java:1143)
04-05 16:31:37.264 10951-10951/com.massimoc.obdreader W/System.err:     at android.widget.AbsListView$PerformClick.run(AbsListView.java:3044)
04-05 16:31:37.264 10951-10951/com.massimoc.obdreader W/System.err:     at android.widget.AbsListView.onTouchUp(AbsListView.java:3845)
04-05 16:31:37.264 10951-10951/com.massimoc.obdreader W/System.err:     at android.widget.AbsListView.onTouchEvent(AbsListView.java:3617)`

**Comment by massimoca** [comment]
Thank you for the notice, I will have a look at it.

**Comment by massimoca** [comment]
By the way what version of Android did you test this on?

**Comment by massimoca** [comment]
Try replacing ConnectThread.java:62 
mSocket = device.createRfcommSocketToServiceRecord(uuid);

mSocket = device.createInsecureRfcommSocketToServiceRecord(uuid);

The insecure socket connection was not my preffered choice but it might be able to fix the issue.

**Comment by pranaypatel512** [comment]
Sure. I will try and get back soon.

**Comment by pranaypatel512** [comment]
Got it. Solved.
But things need to keep in mind while using `createInsecureRfcommSocketToServiceRecord()`.

> createInsecureRfcommSocketToServiceRecord() has of "insecure" the key the devices are using to communicate, which is, below Bluetooth 2.1, not encrypted. That is what is "unsecure".

Check pull request [#2](https://github.com/massimoca/OBDReader/pull/2) for same.

**Comment by massimoca** [comment]
Thank you for checking, it's strange that this bug occurs on Android 6.0.1. When I first started developing this app, I was targetting devices up to Android 5.0. On my [older Android phone](http://www.lg.com/us/cell-phones/lg-LS720-Titanium-Silver-optimus-f3) it seems to function using the secure connection.
